<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'candidat' => [[], ['_controller' => 'App\\Controller\\CandidatController::index'], [], [['text', '/candidat']], [], []],
    'app_candidat_candidatprofil' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::candidatProfil'], [], [['text', '/profil'], ['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], []],
    'app_candidat_candidats' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::candidats'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], []],
    'app_candidat_deletecandidat' => [['id'], ['_controller' => 'App\\Controller\\CandidatController::deleteCandidat'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/candidat']], [], []],
    'client' => [[], ['_controller' => 'App\\Controller\\ClientController::client'], [], [['text', '/client']], [], []],
    'customer' => [[], ['_controller' => 'App\\Controller\\CustomerController::customer'], [], [['text', '/customer']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'manager' => [[], ['_controller' => 'App\\Controller\\ManagerController::index'], [], [['text', '/manager']], [], []],
    'mission' => [[], ['_controller' => 'App\\Controller\\MissionController::index'], [], [['text', '/mission']], [], []],
    'app_mission_getmission' => [['id'], ['_controller' => 'App\\Controller\\MissionController::getMission'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], []],
    'app_mission_postulemission' => [['id'], ['_controller' => 'App\\Controller\\MissionController::postuleMission'], [], [['text', '/postuler'], ['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], []],
    'app_mission_deletemission' => [['id'], ['_controller' => 'App\\Controller\\MissionController::deleteMission'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], []],
    'app_mission_missionedit' => [['id'], ['_controller' => 'App\\Controller\\MissionController::missionEdit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/mission']], [], []],
    'profil' => [[], ['_controller' => 'App\\Controller\\ProfilController::index'], [], [['text', '/profil']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
