<?php

namespace ContainerTAUczwA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ManagerController' shared autowired service.
     *
     * @return \App\Controller\ManagerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ManagerController.php';

        $container->services['App\\Controller\\ManagerController'] = $instance = new \App\Controller\ManagerController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\ManagerController', $container));

        return $instance;
    }
}
