<?php

namespace ContainerOb14xVx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidatControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CandidatController' shared autowired service.
     *
     * @return \App\Controller\CandidatController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CandidatController'] = $instance = new \App\Controller\CandidatController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Controller\\CandidatController', $container));

        return $instance;
    }
}
