<?php

namespace ContainerOb14xVx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CustomerRepository' shared autowired service.
     *
     * @return \App\Repository\CustomerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CustomerRepository'] = new \App\Repository\CustomerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
