<?php

namespace ContainerOb14xVx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagerRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ManagerRepository' shared autowired service.
     *
     * @return \App\Repository\ManagerRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ManagerRepository'] = new \App\Repository\ManagerRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
