<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerERxeebL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerERxeebL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerERxeebL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerERxeebL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerERxeebL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ERxeebL',
    'container.build_id' => 'c239ea42',
    'container.build_time' => 1610487610,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerERxeebL');
