<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3td5ROG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3td5ROG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3td5ROG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3td5ROG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3td5ROG\App_KernelDevDebugContainer([
    'container.build_hash' => '3td5ROG',
    'container.build_id' => 'aa9f21d7',
    'container.build_time' => 1610492394,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3td5ROG');
