<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIwdRPzx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIwdRPzx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIwdRPzx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIwdRPzx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIwdRPzx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IwdRPzx',
    'container.build_id' => 'd2dfdf12',
    'container.build_time' => 1610342795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIwdRPzx');
