<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mission extends \App\Entity\Mission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'describ', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'place', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'durate', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'candidats'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'describ', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'place', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'durate', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'candidats'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getClient(): ?\App\Entity\Client
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(?\App\Entity\Client $client): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescrib(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescrib', []);

        return parent::getDescrib();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescrib(string $describ): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescrib', [$describ]);

        return parent::setDescrib($describ);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlace', []);

        return parent::getPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlace(string $place): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlace', [$place]);

        return parent::setPlace($place);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurate', []);

        return parent::getDurate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurate(string $durate): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurate', [$durate]);

        return parent::setDurate($durate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(int $price): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidats(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidats', []);

        return parent::getCandidats();
    }

    /**
     * {@inheritDoc}
     */
    public function addCandidat(\App\Entity\Candidat $candidat): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCandidat', [$candidat]);

        return parent::addCandidat($candidat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCandidat(\App\Entity\Candidat $candidat): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCandidat', [$candidat]);

        return parent::removeCandidat($candidat);
    }

}
